# Generated by Django 4.2.3 on 2023-08-01 16:49

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model", models.CharField(max_length=45)),
                (
                    "brand",
                    models.CharField(
                        choices=[
                            ("ford", "Ford"),
                            ("chevy", "Chevy"),
                            ("toyota", "Toyota"),
                            ("volks", "Volks"),
                        ],
                        max_length=45,
                    ),
                ),
                (
                    "main_color",
                    models.CharField(
                        choices=[
                            ("red", "Red"),
                            ("blue", "Blue"),
                            ("black", "Black"),
                            ("yellow", "Yellow"),
                            ("white", "White"),
                        ],
                        max_length=25,
                    ),
                ),
                ("value", models.PositiveIntegerField()),
                ("production_cost", models.PositiveIntegerField()),
                ("transportation_cost", models.PositiveIntegerField()),
            ],
        ),
    ]
